### PR TITLE
Add Hungarian translation

### PR DESCRIPTION
**Pull request by BathoryPeter**
and add Translation section in README.MD

### CODE REVIEW

**Comment by tmizu23** [comment]
@BathoryPeter 
Thanks for your contribution.

Japanese translation by windows linguist did not work well because of a newline or 2-byte character in the source code, so I changed it.In addition, there was a mistake in the description of how to use the system, so the source code has been changed.

Can you check if Hungarian is displayed correctly? The commit is #33

If there is no problem, I will prepare to release it.

**Comment by BathoryPeter** [comment]
@tmizu23 Thanks for letting me know.

With #33 every new line has doubled for me. I don't really know what causes it. Python 3 fully supports Unicode so 2-byte characters shouldn't be problem. Currently .py files using mixed Windows and Unix new line characters. It would be worth getting rid of CRLF.

I'm on Ubuntu, using QGIS 3.29:
Képernyőkép ekkor: 2022-12-12 10-03-58

**Comment by tmizu23** [comment]
@BathoryPeter 
Thanks for confirming.
I fix it by removing newline in linguist.
This will probably work.
updated #33

**Comment by BathoryPeter** [comment]
Thanks, its much better now!

Képernyőkép ekkor: 2022-12-12 10-55-21
As you can see on this screenshot, not just the first but the second line also get bold, while HTML markup in .ts file is correct. This seems to be a Qt bug.

**Comment by tmizu23** [comment]
It seems to be a bug in windows Qt that makes it Bold. The same thing happened in Japanese.
On my Mac it was displayed correctly.

Now I will prepare for the release.
Thank you so much.

**Comment by BathoryPeter** [comment]
Did you also experience it on Windows? I only have Linux machines.
Maybe we can ask QGIS devs as they are also using HTML tooltips.

Thanks for the great plugin and the new relese!

**Pull request merged**
